# Generated by Django 5.1.7 on 2026-09-25 07:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('hire_requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField()),
                ('body', models.TextField()),
                ('hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='accounts.profile')),
                ('hire_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='hire_requests.hirerequest')),
                ('hirer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to='accounts.profile')),
            ],
            options={
                'indexes': [models.Index(fields=['coach'], name='reviews_coach_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='reviews_rating_range')],
            },
        ),
    ]
