# Generated by Django 5.1.7 on 2026-09-25 07:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HireRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_hirer_kind', models.CharField(choices=[('player', 'Player'), ('parent', 'Parent'), ('club', 'Club')], max_length=10)),
                ('snapshot_club_name', models.CharField(blank=True, max_length=120, null=True)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hire_requests_received', to='accounts.profile')),
                ('hirer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hire_requests_sent', to='accounts.profile')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hire_requests', to='listings.listing')),
            ],
            options={
                'indexes': [models.Index(fields=['coach', 'status'], name='hire_requests_coach_status_idx'), models.Index(fields=['hirer', 'status'], name='hire_requests_hirer_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('hirer_id', models.F('coach_id')), _negated=True), name='hire_requests_no_self'), models.CheckConstraint(condition=models.Q(models.Q(('snapshot_club_name__isnull', False), ('snapshot_hirer_kind', 'club')), models.Q(('snapshot_hirer_kind', 'club'), _negated=True), _connector='OR'), name='hire_requests_snapshot_club'), models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('hirer', 'coach'), name='hire_requests_one_pending_per_pair')],
            },
        ),
    ]
