# Generated by Django 5.1.7 on 2026-09-25 07:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('hire_requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hire_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='hire_requests.hirerequest')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='accounts.profile')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['hire_request', 'created_at'], name='chat_message_thread_idx')],
            },
        ),
    ]
