# Generated by Django 5.1.7 on 2026-09-25 07:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('hire_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_paise', models.PositiveIntegerField()),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('created', 'Created'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='created', max_length=12)),
                ('razorpay_order_id', models.CharField(max_length=40, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('rate_rupees', models.PositiveIntegerField()),
                ('rate_unit', models.CharField(choices=[('session', 'Session'), ('month', 'Month')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_received', to='accounts.profile')),
                ('hire_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='hire_requests.hirerequest')),
                ('hirer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_made', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_paise', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('due', 'Due'), ('paid', 'Paid')], default='due', max_length=8)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('utr', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='accounts.profile')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts_marked', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payout', to='payments.payment')),
            ],
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['hirer', 'created_at'], name='payments_hirer_created_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['coach', 'status'], name='payments_coach_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'failed'), _negated=True), fields=('hire_request',), name='payments_one_active_per_hire'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paise__gt', 0)), name='payments_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'INR')), name='payments_currency_inr'),
        ),
        migrations.AddConstraint(
            model_name='payout',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paise__gt', 0)), name='payouts_amount_positive'),
        ),
    ]
