# Generated by Django 5.1.7 on 2026-09-25 07:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoachRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=100)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_roles', to='catalog.sport')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sport', 'slug'), name='coach_roles_sport_slug_uniq')],
            },
        ),
    ]
