# Generated by Django 5.1.7 on 2026-09-25 07:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('years_experience', models.PositiveSmallIntegerField()),
                ('city', models.CharField(max_length=80)),
                ('remote_ok', models.BooleanField(default=False)),
                ('rate_rupees', models.PositiveIntegerField()),
                ('rate_unit', models.CharField(choices=[('session', 'Session'), ('month', 'Month')], max_length=10)),
                ('available', models.BooleanField(default=True)),
                ('bio', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='accounts.profile')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='catalog.sport')),
            ],
        ),
        migrations.CreateModel(
            name='ListingRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.coachrole')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_roles', to='listings.listing')),
            ],
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['sport', 'available'], name='listings_available_sport_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['city'], name='listings_city_idx'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(('years_experience__gte', 0), ('years_experience__lte', 60)), name='listings_years_check'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(('rate_rupees__gt', 0)), name='listings_rate_check'),
        ),
        migrations.AddConstraint(
            model_name='listingrole',
            constraint=models.UniqueConstraint(fields=('listing', 'coach_role'), name='listing_roles_uniq'),
        ),
    ]
