# Generated by Django 5.1.7 on 2026-09-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='rating_avg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
